### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by nozge** [SampathTharanga/POS-System-V-1.0#1]
Cannot load database into the VStudio!

**Comment by wilfred05777** [comment]
hi, what is the password for the login? as super user?
thanks in advance

**Comment by nozge** [comment]
I dont know the password i cant even connect to it*

**Comment by muhammadhamxa1** [comment]
i install your project ! i apply user:Admin pas: Admin but can't login :(

**Comment by AdnanMuhib** [comment]
hi @nozge , @wilfred05777 , @muhammadhamxa1 
I just ran the project using installer and following error occured
![Login Error](https://user-images.githubusercontent.com/18069154/54147424-f54dc600-4453-11e9-8f9a-e806d6dcb217.PNG)
From the error it is clear that there is issue of username and password for specific user.
So the solution is simple,
Run the project using it's Source code in Visual Studio,
change the connection string in App.config file to 

`<add name="DBConnection" connectionString="Data Source=.;Initial Catalog=pos_system;Integrated Security=True; MultipleActiveResultSets=True;"`

Then Build and run the project.

**Comment by SampathTharanga** [comment]
@nozge , @wilfred05777 , @muhammadhamxa1

i use the "ODBC" connction to connect DB. So, first create ODBC connection and try to login. Login Id and password is "genesip". You can see it after the refer "App.config" file. Also, you must place the Database to correct SQL sever location.

Like this image,
https://www.sqlshack.com/wp-content/uploads/2017/08/c-users-marko-appdata-local-microsoft-windows-ine.png

https://github.com/SampathTharanga/POS-System-V-1.0/blob/master/SOURCE/POS_System%20V%201.1/POS_System/App.config
