### ISSUE TITLE
database connection

### ISSUE THREAD

**Issue by carleefayakasai** [SampathTharanga/POS-System-V-1.0#3]
please help me connect to Database I am running vs2015 and SQL sever 2014

**Comment by SampathTharanga** [comment]
Please follow the below steps to connect the database with software.
1. Import the database to SQL server
2. Create an ODBC connection with these details. => Server = .\; Database = pos_system; User Id = genesip; Password = genesip
3. Now it's working correctly.
Good Luck!

**Comment by SampathTharanga** [comment]
Also You can refer below guides to configuration the system.

**POS-System-V-1.2**: https://github.com/SampathTharanga/POS-System-V-1.2
**System configuration guide**: https://github.com/SampathTharanga/POS-System-V-1.2/blob/main/FOR%20SYSTEM%20ADMINISTRATOR.txt
